### ISSUE TITLE
Understanding output of generRFinder

### ISSUE THREAD

**Issue by kdbchau** [railorena/geneRFinder#1]
Hello,

I'm interested in using geneRFinder for my contigs to predict genes and while the program works fine, I am having trouble understanding the output. I ran it with the example/final_contigs.fasta file with the recommended parameters, but the output is confusing to me. What are the headers supposed to mean? They are just numbers. I see no clear documentation on what the output is and how many genes are produced from one contig, since the names are gone in the output.

**Comment by railorena** [comment]
Hi,
Thank you for the feedback, I did an update about the output, I put more information. If it is not clear, tell me.
If you have another suggestion, I will be glad to listen.
Sorry for the delay in answering.
